apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  labels:
    app: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: dummy-container
        image: 585768171991.dkr.ecr.us-west-2.amazonaws.com/dummy-eks-app
        ports:
        - containerPort: 80
